google/sqlcommenter

python/sqlcommenter-python/google/__init__.py

For the __init__.py in the main package, this change follows
the advisory at
https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages
to add the the line
__import__('pkg_resources').declare_namespace(__name__)
to ONLY the main package's directory i.e. in the same directory
level as setup.py
Fixes #4

python: add pkg_resources in the namespace __init__.py

---

nodejs/sqlcommenter-nodejs/packages/sqlcommenter-knex/package-lock.json
nodejs/sqlcommenter-nodejs/packages/sqlcommenter-knex/package.json
nodejs/sqlcommenter-nodejs/packages/sqlcommenter-sequelize/package-lock.json
nodejs/sqlcommenter-nodejs/packages/sqlcommenter-sequelize/package.json

@opencensus/nodejs, @opencensus/propagation-tracecontext, and @opentelemetry/core are actually required at runtime, regardless of whether or not `tracestate`/`traceparent` labels are requested. See #23 
Adding to `peerDependencies` so that package using these sqlcommenter libraries would need to install these dependencies and then both packages would share that same version. I think in the long run, these dependencies should be optional and only `require()`d in the code paths that use these features.

node: add OpenTelemetry/OpenCensus deps to peerDependencies

---

nodejs/sqlcommenter-nodejs/samples/express-opentelemetry/README.md
nodejs/sqlcommenter-nodejs/samples/express-opentelemetry/package-lock.json
nodejs/sqlcommenter-nodejs/samples/express-opentelemetry/package.json
nodejs/sqlcommenter-nodejs/samples/express-opentelemetry/sequelizeModels.js
nodejs/sqlcommenter-nodejs/samples/express-opentelemetry/sequelizeServer.js
nodejs/sqlcommenter-nodejs/samples/express-opentelemetry/util.js

Depends on #26
Adds a sample app as an example for users. See `README.md` for details.
This sample lets you easily verify the OpenTelemetry integration is working. I will link to this sample in the documentation.

node: add sequelize + express + opentelemetry sample app

---

python/sqlcommenter-python/google/cloud/sqlcommenter/__init__.py

Tests were previously failing because `psycopg2.__libpq_version__` is an int:
```
======================================================================
ERROR: test_dbapi_threadsafety (tests.psycopg2.tests.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/aaronabbott/src/tests/psycopg2/tests.py", line 54, in test_dbapi_threadsafety
with_dbapi_threadsafety=True,
File "/home/aaronabbott/src/tests/psycopg2/tests.py", line 36, in assertSQL
self.assertEqual(cursor.execute(None, 'SELECT 1;'), 'worked')
File "/home/aaronabbott/src/.tox/py36-psycopg2/lib/python3.6/site-packages/google/cloud/sqlcommenter/psycopg2/extension.py", line 70, in execute
sql += generate_sql_comment(**data)
File …
```

python: fix broken tests

---

python/sqlcommenter-python/.gitignore
python/sqlcommenter-python/README.md
python/sqlcommenter-python/google/cloud/sqlcommenter/django/middleware.py
python/sqlcommenter-python/google/cloud/sqlcommenter/opentelemetry.py
python/sqlcommenter-python/google/cloud/sqlcommenter/psycopg2/extension.py
python/sqlcommenter-python/google/cloud/sqlcommenter/sqlalchemy/executor.py
python/sqlcommenter-python/setup.py
python/sqlcommenter-python/tests/compat.py
python/sqlcommenter-python/tests/django/tests.py
python/sqlcommenter-python/tests/generic/test_opentelemetry.py
python/sqlcommenter-python/tests/opentelemetry_mock.py
python/sqlcommenter-python/tests/psycopg2/tests.py
python/sqlcommenter-python/tests/sqlalchemy/tests.py
python/sqlcommenter-python/tox.ini

Add support for OpenTelemetry trace context in python.
- OpenTelemetry only supports python3+, so there is some complication there around the test code.
- If the user tries to use OpenCenus AND OpenTelemetry, we log a warning since they write to the same sql comment
- Passing tox tests run locally for python 2.7, 3.5, 3.6, and 3.7
- Tested psycopg2 manually with a script writing to cloud monitoring. See next PR https://github.com/google/sqlcommenter/pull/39

python: Add OpenTelemetry support

---

ruby/sqlcommenter-ruby/sqlcommenter_rails/README.md
ruby/sqlcommenter-ruby/sqlcommenter_rails_demo/README.md

This PR updates the `sqlcommeter_rails` readme so that it references the `modulitos` fork instead of the `glebm` fork. The `modulitos` fork makes the same changes as the `glebm` fork, except that it rebases the latest changes from the `master` branch of the `marginalia` repo, so that we'll have support for Rails 6.
For reference, here's the original commit where this README was originally updated:
https://github.com/google/sqlcommenter/commit/70d62f0b71dc28056aaac26537fdf98aeaecd17b
Here's the PR to merge the `modulitos` fork into the `master` branch of `marginalia`:
https://github.com/basecamp/marginalia/pull/130
I am working with the `marginalia` maintainers to get that PR merged in. When I do, I will update this README so that we can remove this extra step of using a `marginalia` fork …

docs(sqlcommenter_rails/README): update marginalia fork to modulitos

---

python/sqlcommenter-python/README.md
python/sqlcommenter-python/google/cloud/sqlcommenter/fastapi.py
python/sqlcommenter-python/google/cloud/sqlcommenter/sqlalchemy/executor.py
python/sqlcommenter-python/setup.py
python/sqlcommenter-python/tests/fastapi/app.py
python/sqlcommenter-python/tests/fastapi/tests.py
python/sqlcommenter-python/tests/sqlalchemy/tests.py

Can be easily extensible for other ASGI frameworks.

Add FastAPI support with an ASGI Middleware

---

python/sqlcommenter-python/google/cloud/sqlcommenter/psycopg2/extension.py
python/sqlcommenter-python/tests/psycopg2/tests.py

At present we are appending comments to the SQL Statements after semi-colon `;`.
For Example:
```
SELECT 1; /*db_driver='driver'*/
```
This comment would not be part of the SQL Statement as `;` acts as a delimiter and hence won't associate with the comment.
This PR fixes that by:
1. removing spaces from end of the line.
2. if the last character is `;`, insert the comment before `;`

Fix SQLCommenter comment addition before end of SQL statement delimiter

---

php/sqlcommenter-php/packages/sqlcommenter-laravel/LICENSE

As this repo's contents will be pushed to `sqlcommenter-php` repo to publish to PHP.

Add LICENSE file for PHP-SQLCommenter

---

python/sqlcommenter-python/google/cloud/sqlcommenter/django/middleware.py
python/sqlcommenter-python/tests/django/settings.py
python/sqlcommenter-python/tests/django/tests.py
python/sqlcommenter-python/tests/django/urls.py
python/sqlcommenter-python/tests/django/views.py

This PR is a fix to issue #117
**Implementation Details:** 
1. Added query wrapper over all connections via the existing SQLCommenter midleware
**Test Cases Added**
1. test_basic_multiple_db_support
2. get_query_other_db

117 django middleware only applies to default database connections ignoring other databases

---

php/sqlcommenter-php/packages/sqlcommenter-laravel/src/Database/Connection.php
php/sqlcommenter-php/packages/sqlcommenter-laravel/src/Utils.php
php/sqlcommenter-php/packages/sqlcommenter-laravel/tests/Unit/UtilsTest.php

I remove/replace unnecessary implementations in PHP (Laravel):
- You don't need to wrap functions for example `selectOne`, `select`, `affectingStatement`. The laravel always calls the `run` function in the Connection class.
- `&&` is better than the `and` operator because it is different calculating order in an expression.
- Added tests because placeholders (`?`) and named placeholders (`:named`) are not ensured in the test.
- In using `#` as a comment-out, it is confusing for the attribution feature in PHP, therefore `//` is better than `#`.

Refactor: Remove/Replace unnecessary implementations in PHP (Laravel)

---

go/go-sql/README.md
go/go-sql/go-sql.go
go/go-sql/go-sql_test.go
go/go-sql/go.mod
go/go-sql/go.sum

This PR refactors go-sql and updates the mod to live go peer packages

go-sql refactoring

---

python/sqlcommenter-python/google/cloud/sqlcommenter/fastapi.py
python/sqlcommenter-python/tests/fastapi/app.py
python/sqlcommenter-python/tests/fastapi/tests.py

This commit changes the FastAPI middleware so that the `"route"` info is
now optional. If it is not present, the SQL comment will not have the
controller/route info.
This info is always present in FastAPI routes. However, Starlette-based
routes (FastAPI can mount Starlette apps as sub-applications) do not and
would crash when the middleware tried to extract the information.
Fixes #133

fix: handle Starlette routes in FastAPI middleware

---

go/samples/http/.gitignore
go/samples/http/todos/controller.go

Fixed memory leak in sample application by adding `rows.Close()` calls in various places

Go samples/http `defer rows.Close()`

---

go/database/sql/go-sql.go
go/database/sql/go-sql_test.go

this PR adds the database-type in the _driver_ tag in this form: `database/sql:{driverName}`. Includes updates to tests

database type in driver tag

---

ruby/sqlcommenter-ruby/README.md
ruby/sqlcommenter-ruby/sqlcommenter_rails/README.md
ruby/sqlcommenter-ruby/sqlcommenter_rails_demo/README.md

This PR updates the Ruby docs to leverage the support Rails has recently provided for SQLCommenter. This will facilitate adoption of SQLCommenter for folks who aren't familiar with how SQLCommenter support has changed across Rails versions.
Note that the current docs are not compatible with Rails versions 7.0 and up. This PR makes the following changes to bring them up to date:
1.  For Rails >=7.1, include docs about how SQLCommenter is now fully supported as the default formatter
- Support was added in [this PR](https://github.com/rails/rails/pull/45081), and it will be the default formatter as well (added in [this PR](https://github.com/rails/rails/pull/46180)).
2. For Rails 7.0, include docs on the [PlanetScale SQLCommenter gem](https://github.com/planetscale/activerecord-sql_commenter# …

Ruby on Rails documentation updates

---

go/core/core.go

Fixes https://github.com/google/sqlcommenter/issues/216

Always escape values in comments as per specification

---

go/core/core.go
go/core/core_test.go

- Updated the library with comments.
- Added unit tests for few methods of the core library.

Add comments and unittests to go-sqlcommenter-core

---

.github/workflows/go-sql-tests.yaml

There were few libraries CI missing. 
Added `Build` and `Test` for all libraries.

Update go test pipeline to build and test all libraries

---

go/database/sql/connection_test.go
go/database/sql/go.mod
go/database/sql/go.sum

- Update SQLCommenter database/sql package to use core-1.2.
- Fixed unit tests to accommodate new version of core.

Fix SQLCommenter database/sql test

---

go/database/sql/connection.go
go/database/sql/connection_test.go

This adds the `controller` comment to the Go library. `EnableController` was already available on the configuration, but it was not added to the SQL comments.
Closes https://github.com/google/sqlcommenter/issues/279

fix: Add Go controller comment
